networks:
  kongair-net:
    name: kongair-net
    driver: bridge
    external: false

services:
 kongair-experience:
  build:
    context: ./services/experience
    dockerfile: Dockerfile
  platform: linux/arm64
  container_name: kongair-experience
  hostname: experience.kongair
  restart: on-failure
  networks:
    - kongair-net
  ports:
   - 5050:4000

 kongair-customers:
  build:
    context: ./services/sales/customer
    dockerfile: Dockerfile
  platform: linux/arm64
  container_name: kongair-customers
  hostname: customers.kongair
  restart: on-failure
  networks:
    - kongair-net
  ports:
   - 5051:3000

 kongair-flights:
  build:
    context: ./services/flight-data/flights
    dockerfile: Dockerfile
  platform: linux/arm64
  container_name: kongair-flights
  hostname: flights.kongair
  restart: on-failure
  networks:
    - kongair-net
  ports:
   - 5052:8080

 kongair-routes:
  build:
    context: ./services/flight-data/routes
    dockerfile: Dockerfile
  platform: linux/arm64
  container_name: kongair-routes
  hostname: routes.kongair
  restart: on-failure
  networks:
    - kongair-net
  ports:
   - 5053:8080

 kongair-bookings:
  build:
    context: ./services/sales/bookings
    dockerfile: Dockerfile
  platform: linux/arm64
  container_name: kongair-bookings
  hostname: bookings.kongair
  restart: on-failure
  networks:
    - kongair-net
  ports:
   - 5054:3000

 kongair-seating:
  build:
    context: ./services/seating
    dockerfile: Dockerfile
  platform: linux/arm64
  container_name: kongair-seating
  hostname: seating.kongair
  restart: on-failure
  networks:
    - kongair-net
  ports:
   - 5055:5055
  environment:
    - PORT=5055

 kongair-operations:
  build:
    context: ./services/operations
    dockerfile: Dockerfile
  platform: linux/arm64
  container_name: kongair-operations
  hostname: operations.kongair
  restart: on-failure
  networks:
    - kongair-net
  ports:
   - 5056:5056
  environment:
    - PORT=5056

 kongair-ancillary:
  build:
    context: ./services/ancillary
    dockerfile: Dockerfile
  platform: linux/arm64
  container_name: kongair-ancillary
  hostname: ancillary.kongair
  restart: on-failure
  networks:
    - kongair-net
  ports:
   - 5057:5057
  environment:
    - PORT=5057

