name: Apply Terraform

on:
  push:
    paths:
      - 'infrastructure/terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      working-directory: infrastructure/terraform
      run: terraform init
      env:
        TF_VAR_PERSONAL_ACCESS_TOKEN: ${{ secrets.KONNECT_PAT }}

    - name: Apply Terraform
      working-directory: infrastructure/terraform
      run: terraform apply -auto-approve -var "personal_access_token=${{ secrets.KONNECT_PAT }}"
      env:
        TF_VAR_PERSONAL_ACCESS_TOKEN: ${{ secrets.KONNECT_PAT }}