name: Build Docker Images

on:
  push:
    branches:
      - "main"
      - "act2-standardized-services"
    paths:
      - 'services/**'
      - 'traffic-injector/**'
      - '.github/workflows/docker.yaml'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - dir: services/flight-data
            name: flights
          - dir: services/flight-data
            name: routes
          - dir: services/sales
            name: bookings
          - dir: services/sales
            name: customer
          - dir: services/experience
            name: experience
          - dir: services/seating
            name: seating
          - dir: services/operations
            name: operations
          - dir: services/ancillary
            name: ancillary
          - dir: traffic-injector
            name: traffic-injector
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "${{ matrix.app.dir }}"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/kongair-${{ matrix.app.name }}:latest
